part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const LOGIN = _Paths.LOGIN;
  static const DASHBOARD = _Paths.DASHBOARD;
  static const SIGN_UP = _Paths.SIGN_UP;
  static const DETAIL_PRODUCT = _Paths.DETAIL_PRODUCT;
  static const ADD_CLIENT = _Paths.ADD_CLIENT;
  static const ADD_ORDER = _Paths.ADD_ORDER;
  static const ADD_PRODUCT = _Paths.ADD_PRODUCT;
  static const ADD_SUPPLIER = _Paths.ADD_SUPPLIER;
  static const CLIENT_LIST = _Paths.CLIENT_LIST;
  static const DETAILS_CLIENT = _Paths.DETAILS_CLIENT;
  static const DETAILS_ORDER = _Paths.DETAILS_ORDER;
  static const DETAILS_PRODUCTS = _Paths.DETAIL_PRODUCTS;
  static const DETAILS_SUPPLIER = _Paths.DETAILS_SUPPLIER;
  static const DETAILS_RETURN = _Paths.DETAILS_RETURN;
  static const DETAILS_SUPPLIER_ORDER = _Paths.DETAILS_SUPPLIER_ORDER;
  static const EXPENSE_REPORT = _Paths.EXPENSE_REPORT;
  static const FINAL_INVENTORY = _Paths.FINAL_INVENTORY;
  static const HISTORY = _Paths.HISTORY;
  static const INVENTORY = _Paths.INVENTORY;
  static const LIST_SUPPLIER_ORDER = _Paths.LIST_SUPPLIER_ORDER;
  static const MANAGEMENT_ORDER = _Paths.MANAGEMENT_ORDER;
  static const MANAGEMENT_ROLE = _Paths.MANAGEMENT_ROLE;
  static const NEWSALE = _Paths.NEWSALE;
  static const NOTIFICATION = _Paths.NOTIFICATION;
  static const ORDER_LIST = _Paths.ORDER_LIST;
  static const PRISE_INVENTORY = _Paths.PRISE_INVENTORY;
  static const PRODUCT_LIST = _Paths.PRODUCT_LIST;
  static const PROFILE = _Paths.PROFILE;
  static const RECEPTION = _Paths.RECEPTION;
  static const SETTINGS = _Paths.SETTINGS;
  static const STOCK = _Paths.STOCK;
  static const SUPPLIER_LIST = _Paths.SUPPLIER_LIST;
  static const SUPPLIER_ORDER = _Paths.SUPPLIER_ORDER;
  static const TRACKING_ORDER = _Paths.TRACKING_ORDER;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const LOGIN = '/login';
  static const DASHBOARD = '/dashboard';
  static const SIGN_UP = '/sign-up';
  static const DETAIL_PRODUCT = '/detail-product';
  static const ADD_CLIENT = '/add-client';
  static const ADD_ORDER = '/add-order';
  static const ADD_PRODUCT = '/add-product';
  static const ADD_SUPPLIER = '/add-supplier';
  static const CLIENT_LIST = '/client-list';
  static const DETAILS_CLIENT = '/details-client';
  static const DETAILS_ORDER = '/details-order';
  static const DETAIL_PRODUCTS = '/details-products';
  static const DETAILS_SUPPLIER = '/details-supplier';
  static const DETAILS_RETURN = '/details-return';
  static const DETAILS_SUPPLIER_ORDER = '/details-supplier-order';
  static const EXPENSE_REPORT = '/expense-report';
  static const FINAL_INVENTORY = '/final-inventory';
  static const HISTORY = '/history';
  static const INVENTORY = '/inventory';
  static const LIST_SUPPLIER_ORDER = '/list-supplier-order';
  static const MANAGEMENT_ORDER = '/management-order';
  static const MANAGEMENT_ROLE = '/management-role';
  static const NEWSALE = '/newsale';
  static const NOTIFICATION = '/notification';
  static const ORDER_LIST = '/order-list';
  static const PRISE_INVENTORY = '/prise-inventory';
  static const PRODUCT_LIST = '/product-list';
  static const PROFILE = '/profile';
  static const RECEPTION = '/reception';
  static const SETTINGS = '/settings';
  static const STOCK = '/stock';
  static const SUPPLIER_LIST = '/supplier-list';
  static const SUPPLIER_ORDER = '/supplier-order';
  static const TRACKING_ORDER = '/tracking-order';
}
